`timescale 1ns / 1ps
module offset_clock(
    input  wire        clk,
    input  wire        clken_1hz,
    input  wire        reset,
    input  wire        load,
    input  wire signed [5:0] offset_min,  // Signed: timezone offset minutes from IST (-30, 0, +15, +30)
    input  wire signed [4:0] offset_hrs,  // Signed: timezone offset hours from IST (-11 to +8)
    input  wire [4:0]  hrs,               // Current IST hours (0-23) from utcp_5_30
    input  wire [5:0]  min,               // Current IST minutes (0-59) from utcp_5_30
    input  wire [5:0]  sec,               // Current IST seconds (0-59) from utcp_5_30
    output reg  [4:0]  tzhrs,             // Timezone adjusted hours output (0-23)
    output reg  [5:0]  tzmin,             // Timezone adjusted minutes output (0-59)
    output reg  [5:0]  tzsec             // Timezone adjusted seconds output (0-59)
);

    // -------------------------------------------------------------------------
    // Internal signed registers to hold the LATCHED offset values
    // These are declared signed so that negative offsets (-4, -30 etc.)
    // are stored and used correctly in arithmetic
    // -------------------------------------------------------------------------
    reg signed [5:0] tz_offset_min;
    reg signed [4:0] tz_offset_hrs;

    // -------------------------------------------------------------------------
    // load_d1: load pulse delayed by exactly 1 clock cycle
    // Purpose: After load fires, the latch registers (tz_offset_hrs/min) take
    // 1 cycle to update due to non-blocking assignment (<=).
    // So we delay load by 1 cycle to trigger compute AFTER latch is ready.
    // Timeline:
    //   Cycle 0: load=1  → latch captures new offset (not visible yet this cycle)
    //   Cycle 1: load=0  → tz_offset now has correct value, load_d1=1 triggers compute
    //   Cycle 2: load_d1=0 → back to normal, waits for clken_1hz
    // -------------------------------------------------------------------------
    reg load_d1;

    // -------------------------------------------------------------------------
    // Integer variables for intermediate arithmetic
    // Declared as integer (32-bit signed) so that:
    // 1. Negative intermediate results are handled correctly
    // 2. Overflow/underflow can be detected and corrected before output
    // -------------------------------------------------------------------------
    integer temp_min;
    integer temp_hrs;

    // =========================================================================
    // BLOCK 1: OFFSET LATCH
    // Captures offset_hrs and offset_min ONLY when load pulse fires.
    // load is generated by mode_controller as a falling edge of edit_enable,
    // meaning it fires exactly once when user finishes country selection.
    // These latched values are then used for ALL subsequent TZ calculations
    // until a new country is selected.
    // =========================================================================
    always @(posedge clk or posedge reset) begin
        if (reset) begin
            // On reset: default to IST offset (India = 0,0)
            tz_offset_min <= 6'sd0;
            tz_offset_hrs <= 5'sd0;
        end
        else if (load) begin
            // Capture the new country offset when FSM fires load pulse
            tz_offset_min <= offset_min;
            tz_offset_hrs <= offset_hrs;
        end
        // If neither reset nor load: hold current latched values
    end

    // =========================================================================
    // BLOCK 2: LOAD DELAY (1 cycle)
    // Simply registers the load signal by 1 clock cycle.
    // This ensures that when load_d1 fires, the latch registers above
    // have already settled to their new values (non-blocking assignment delay).
    // =========================================================================
    always @(posedge clk or posedge reset) begin
        if (reset)
            load_d1 <= 1'b0;
        else
            load_d1 <= load;  // load_d1 is always 1 cycle behind load
    end

    // =========================================================================
    // BLOCK 3: TIMEZONE CALCULATION
    // Computes the timezone-adjusted time using latched offsets.
    // Triggered by:
    //   - clken_1hz : normal every-second tick to keep TZ clock running
    //   - load_d1   : immediate update after new country is selected
    //                 (so display updates instantly, not after up to 1 second wait)
    //
    // IMPORTANT - Why $signed({1'b0, min}) and not just $signed(min)?
    //   min is 6 bits [5:0] and unsigned. If min=45 (binary 101101),
    //   $signed(min) would see MSB=1 and treat it as NEGATIVE (-19). Wrong!
    //   Prepending 1'b0 makes it 7 bits (0101101), MSB=0, safely positive.
    //   Then $signed() enables signed arithmetic for the whole expression.
    //   Same logic applies to hrs.
    //
    // IMPORTANT - Why temp_min[5:0] and temp_hrs[4:0] on output?
    //   temp_min/hrs are 32-bit integers. tzmin is 6-bit, tzhrs is 5-bit.
    //   After overflow correction, values are always in valid range (0-59, 0-23)
    //   so upper bits are zero. Explicit slicing avoids width mismatch warnings.
    // =========================================================================
    always @(posedge clk or posedge reset) begin
        if (reset) begin
            tzsec <= 6'd0;
            tzmin <= 6'd0;
            tzhrs <= 5'd0;
        end
        else begin

            // Seconds are the same across all timezones — just copy directly
            tzsec <= sec;

            // Trigger calculation every second OR immediately after country load
            if (clken_1hz || load_d1) begin

                // -----------------------------------------------------------------
                // STEP 1: Add offsets to current IST time
                // $signed({1'b0, min/hrs}) — safely converts unsigned to signed
                // $signed(tz_offset_min/hrs) — ensures signed arithmetic is used
                // Without $signed: -30 would be read as 34, -4 as 28 (wrong!)
                // With    $signed: -30 stays -30,  -4 stays -4  (correct!)
                // -----------------------------------------------------------------
                temp_min = $signed({1'b0, min}) + $signed(tz_offset_min);
                temp_hrs = $signed({1'b0, hrs}) + $signed(tz_offset_hrs);

                // -----------------------------------------------------------------
                // STEP 2: Fix minutes overflow/underflow
                // If offset pushed minutes out of 0-59 range, correct it
                // and carry/borrow 1 hour accordingly.
                // else-if used intentionally: prevents double correction
                // Example +ve: temp_min=75 → temp_min=15, temp_hrs+1
                // Example -ve: temp_min=-30 → temp_min=30, temp_hrs-1
                // -----------------------------------------------------------------
                if (temp_min >= 60) begin
                    temp_min = temp_min - 60;
                    temp_hrs = temp_hrs + 1;  // carry 1 hour forward
                end
                else if (temp_min < 0) begin
                    temp_min = temp_min + 60;
                    temp_hrs = temp_hrs - 1;  // borrow 1 hour backward
                end

                // -----------------------------------------------------------------
                // STEP 3: Fix hours overflow/underflow
                // After minute correction, hours may still be out of 0-23 range.
                // Wrap around: 24 → 0 (next day), -1 → 23 (previous day)
                // else-if used intentionally: prevents double correction
                // Example: temp_hrs=25 → temp_hrs=1
                // Example: temp_hrs=-2 → temp_hrs=22
                // -----------------------------------------------------------------
                if (temp_hrs >= 24)
                    temp_hrs = temp_hrs - 24;  // wrap to next day
                else if (temp_hrs < 0)
                    temp_hrs = temp_hrs + 24;  // wrap to previous day

                // -----------------------------------------------------------------
                // STEP 4: Assign corrected values to outputs
                // Non-blocking assignment (<=) used correctly for output registers
                // Explicit bit slicing [5:0] and [4:0] used to:
                //   1. Avoid width mismatch warnings (integer=32bit, output=5/6bit)
                //   2. Make intent clear — we only need lower bits
                // -----------------------------------------------------------------
                tzmin <= temp_min[5:0];
                tzhrs <= temp_hrs[4:0];

            end
            // If neither clken_1hz nor load_d1: hold current output values
        end
    end

endmodule